name: location
description: This librarie aims at providing you a simple way to get the user location without thinking about permission.
homepage: https://docs.page/Lyokone/flutterlocation
repository: https://github.com/weklean/flutterlocation
version: 5.0.0-dev.9

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: .location_android
      ios:
        default_package: location_ios
      # linux:
      #   default_package: location_linux
      macos:
        default_package: location_macos
      web:
        default_package: location_web
      # windows:
      #   default_package: location_windows

dependencies:
  flutter:
    sdk: flutter
  location_android:
    git:
      url: https://github.com/weklean/flutterlocation
      path: packages/location_android
  location_ios:
    git:
      url: https://github.com/weklean/flutterlocation
      path: packages/location_ios
  location_linux:
    git:
      url: https://github.com/weklean/flutterlocation
      path: location_linux
  location_macos:
    git:
      url: https://github.com/weklean/flutterlocation
      path: packages/location_macos
  location_platform_interface:
    git:
      url: https://github.com/weklean/flutterlocation
      path: location_platform_interface
  location_web:
    git:
      url: https://github.com/weklean/flutterlocation
      path: location_web
  location_windows:
    git:
      url: https://github.com/weklean/flutterlocation
      path: location_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.0
